### PR TITLE
Final improvements - fix events

### PR DESCRIPTION
**Pull request by weiglszonja**
Save Reward, Licking, AirPuff, Light stimulus sensor output from PicoScope as TimeSeries
link the time series from the TimeIntervals table
Also contains the updates after running conversion from fresh environment (frozen_dependencies.txt)

### CODE REVIEW

**Comment by weiglszonja** [comment]
@alessandratrapani example [files](https://us-east-2.console.aws.amazon.com/s3/buckets/catalystneuro-processing?region=us-east-2&bucketType=general&prefix=dombeck-lab-to-nwb/&showversions=false)

**Comment by weiglszonja** [comment]
@alessandratrapani can you check these example files? I've rerun the conversion and awaiting this approval to upload the files 🙈 let me know if you see something else that could be improved.

**Review by alessandratrapani — APPROVED** [review]
Sorry! Checked both files looks good!

**Comment by weiglszonja** [comment]
Thank you!

**Pull request merged**
